<H1>1.Importing Libraries</H1>

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import os

<H1>Import Data Files</H1>

In [3]:
# Creating Path
path = r'C:\Users\supri\Desktop\Supriya\DataAnalysis\Project\Data Immersion\Achievement 1-2\Instacart_Basket_Analysis'

In [5]:
# Importing orders_products_merged_derived.pkl File
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data' , 'Prepared Data' , 'ords_prods_merged_derived.pkl'))

In [6]:
# create a subset
df=ords_prods_merge[:1000000]

In [8]:
#Check output
df.shape

(1000000, 21)

In [9]:
df.head(10)

,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_days_of_week,order_hour_of_day,days_since_prior_order,first_time_customers,product_id,...,reordered,product_name,aisle_id,department_id,prices,match,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,0,2539329,1,prior,1,2,8,NaN,True,196,...,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,0,2539329,1,prior,1,2,8,NaN,True,14084,...,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,0,2539329,1,prior,1,2,8,NaN,True,12427,...,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders
3,0,2539329,1,prior,1,2,8,NaN,True,26088,...,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders
4,0,2539329,1,prior,1,2,8,NaN,True,26405,...,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders
5,1,2398795,1,prior,2,3,7,15.0,False,196,...,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest Days,Average orders
6,1,2398795,1,prior,2,3,7,15.0,False,10258,...,0,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest Days,Average orders
7,1,2398795,1,prior,2,3,7,15.0,False,12427,...,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest Days,Average orders
8,1,2398795,1,prior,2,3,7,15.0,False,13176,...,0,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest Days,Average orders
9,1,2398795,1,prior,2,3,7,15.0,False,26088,...,1,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Slowest Days,Average orders

<H3>2. Grouping Data with Pandas</H3>

In [10]:
# Grouping data in pandas follows a set of logical steps
# First, split the data into groups based on given criteria
# Next, apply a function to these groups
# Lastly, combine the results to see what was created

In [11]:
# The 'groupby()' function will group a given dataframe by a given column
df.groupby('product_name')

In [12]:
# The function created a pandas object
# But, the output is not visible yet
# It needs next step, like aggregating the data or applying a function, before seeing the results
# groupby() should always be used as part of a series of steps

<H3>3.Aggregating Data with agg()</H3>

In [13]:
# Aggregating functions create summaries of selected columns and store these summary values in new columns
# These summaries usually take the form of a descriptive statistic

In [14]:
# The 'agg()' function is used for aggregation
# It is used to produce a single descriptive statistic for the 'order_number' column
# If you were to calculate the mean of the 'order_number' column grouped by the 'department_id' column, you can compare user orders in each department
# 'order_number' refers to the number of orders placed by a given user
# The process is as follows:
# 1. Split the data into groups based on 'department_id'
# 2. Apply the agg() function to each group to obtain the mean values for the 'order_number' column
df.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [15]:
# The groupby() function is assigned to the df dataframe, creating a pandas object for the 'department_id'
# The agg() function is applied to this object, returning the mean of the given column 'order_id'
# The result is the average number of orders per user for each department id

In [16]:
# The aggregation can be conducted without the use of the agg() function using the mean()
df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [17]:
# Observation -The difference in syntax between the two methods:
# 1. When using agg(), put the column you want to aggregate inside the parenthesis of the agg()
# 2. When using mean(), simply index the column with square brackets, then follow it with the function you want to use after the dot

<H4>Perform multiple aggregations at once</H4>

In [18]:
# You can perform multiple aggregations at once
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

<H4>4. Aggregating Data with transform()</H4>

In [19]:
#Loyal customers frequently return to use the service or buy products.
#To help the business strategy team implement a bonus program, we'll identify these customers using the transform() function to find the maximum frequency of order_number. 
#Then, we'll use loc() to flag them as 'loyal' or not.

In [20]:
# Flag Criteria:
# 1. If the maximum orders the user has made is over 40, then the customer will be labeled a 'Loyal customer'
# 2. If the maximum orders the user has made is over 10 but less than or equal to 40, then the customer will be labeled a 'Regular customer'
# 3. If the maximum orders the user has made is less than or equal to 10, then the customer will be labeled a 'New customer'

In [22]:
# Steps
# 1. Split the data in groups based on the 'user_id' column
# 2. Apply the transform() function on the 'order_number' column to generate the maximum orders for each user
# 3. Create a new column, 'max_order,' into which you'll place the results of your aggregation
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [23]:
ords_prods_merge.head(15)

,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_days_of_week,order_hour_of_day,days_since_prior_order,first_time_customers,product_id,...,product_name,aisle_id,department_id,prices,match,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,True,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,True,14084,...,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,True,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,True,26088,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,True,26405,...,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
5,1,2398795,1,prior,2,3,7,15.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest Days,Average orders,10
6,1,2398795,1,prior,2,3,7,15.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
7,1,2398795,1,prior,2,3,7,15.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
8,1,2398795,1,prior,2,3,7,15.0,False,13176,...,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest Days,Average orders,10
9,1,2398795,1,prior,2,3,7,15.0,False,26088,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
10,1,2398795,1,prior,2,3,7,15.0,False,13032,...,Cinnamon Toast Crunch,121,14,4.0,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
11,2,473747,1,prior,3,3,12,21.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest Days,Most orders,10
12,2,473747,1,prior,3,3,12,21.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest Days,Most orders,10
13,2,473747,1,prior,3,3,12,21.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest Days,Most orders,10
14,2,473747,1,prior,3,3,12,21.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Slowest Days,Most orders,10

In [24]:
# Now we have a new 'max_order' column in our dataframe
# Each value in this column corresponds to the maximum number of orders made by each user id

In [25]:
# You can check the output by printing the head of the dataframe with an argument of, say 100
ords_prods_merge.head(100)

,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_days_of_week,order_hour_of_day,days_since_prior_order,first_time_customers,product_id,...,product_name,aisle_id,department_id,prices,match,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,True,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,True,14084,...,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,True,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,True,26088,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,True,26405,...,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,14,738281,2,prior,4,2,10,8.0,False,21150,...,Fire Grilled Steak Bowl,38,1,5.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
96,15,1673511,2,prior,5,3,11,8.0,False,47144,...,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,Mid-range product,Regularly busy,Slowest Days,Most orders,14
97,15,1673511,2,prior,5,3,11,8.0,False,5322,...,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,Low-range product,Regularly busy,Slowest Days,Most orders,14
98,15,1673511,2,prior,5,3,11,8.0,False,17224,...,Oats & Honey Gluten Free Granola,3,19,1.6,both,Low-range product,Regularly busy,Slowest Days,Most orders,14
99,15,1673511,2,prior,5,3,11,8.0,False,38656,...,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,Low-range product,Regularly busy,Slowest Days,Most orders,14

In [27]:
# However, the current settings won't allow you to see all 100
# This can be changed via the following code:
pd.options.display.max_rows = None

In [28]:
ords_prods_merge.head(100)

,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_days_of_week,order_hour_of_day,days_since_prior_order,first_time_customers,product_id,...,product_name,aisle_id,department_id,prices,match,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,2539329,1,prior,1,2,8,NaN,True,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,0,2539329,1,prior,1,2,8,NaN,True,14084,...,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
2,0,2539329,1,prior,1,2,8,NaN,True,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
3,0,2539329,1,prior,1,2,8,NaN,True,26088,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
4,0,2539329,1,prior,1,2,8,NaN,True,26405,...,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
5,1,2398795,1,prior,2,3,7,15.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest Days,Average orders,10
6,1,2398795,1,prior,2,3,7,15.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
7,1,2398795,1,prior,2,3,7,15.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
8,1,2398795,1,prior,2,3,7,15.0,False,13176,...,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest Days,Average orders,10
9,1,2398795,1,prior,2,3,7,15.0,False,26088,...,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
10,1,2398795,1,prior,2,3,7,15.0,False,13032,...,Cinnamon Toast Crunch,121,14,4.0,both,Low-range product,Regularly busy,Slowest Days,Average orders,10
11,2,473747,1,prior,3,3,12,21.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest Days,Most orders,10
12,2,473747,1,prior,3,3,12,21.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest Days,Most orders,10
13,2,473747,1,prior,3,3,12,21.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest Days,Most orders,10
14,2,473747,1,prior,3,3,12,21.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Slowest Days,Most orders,10
15,2,473747,1,prior,3,3,12,21.0,False,30450,...,Creamy Almond Butter,88,13,3.2,both,Low-range product,Regularly busy,Slowest Days,Most orders,10
16,3,2254736,1,prior,4,4,7,29.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Least Day,Slowest Days,Average orders,10
17,3,2254736,1,prior,4,4,7,29.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Least Day,Slowest Days,Average orders,10
18,3,2254736,1,prior,4,4,7,29.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Least Day,Slowest Days,Average orders,10
19,3,2254736,1,prior,4,4,7,29.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Least Day,Slowest Days,Average orders,10
20,3,2254736,1,prior,4,4,7,29.0,False,26405,...,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Least Day,Slowest Days,Average orders,10
21,4,431534,1,prior,5,4,15,28.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Least Day,Slowest Days,Most orders,10
22,4,431534,1,prior,5,4,15,28.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Least Day,Slowest Days,Most orders,10
23,4,431534,1,prior,5,4,15,28.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Least Day,Slowest Days,Most orders,10
24,4,431534,1,prior,5,4,15,28.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Least Day,Slowest Days,Most orders,10
25,4,431534,1,prior,5,4,15,28.0,False,10326,...,Organic Fuji Apples,24,4,2.7,both,Low-range product,Least Day,Slowest Days,Most orders,10
26,4,431534,1,prior,5,4,15,28.0,False,17122,...,Honeycrisp Apples,24,4,14.0,both,Mid-range product,Least Day,Slowest Days,Most orders,10
27,4,431534,1,prior,5,4,15,28.0,False,41787,...,Bartlett Pears,24,4,5.0,both,Low-range product,Least Day,Slowest Days,Most orders,10
28,4,431534,1,prior,5,4,15,28.0,False,13176,...,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Least Day,Slowest Days,Most orders,10
29,5,3367565,1,prior,6,2,7,19.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
30,5,3367565,1,prior,6,2,7,19.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
31,5,3367565,1,prior,6,2,7,19.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Regularly busy,Average orders,10
32,5,3367565,1,prior,6,2,7,19.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
33,6,550135,1,prior,7,1,9,20.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
34,6,550135,1,prior,7,1,9,20.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
35,6,550135,1,prior,7,1,9,20.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
36,6,550135,1,prior,7,1,9,20.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
37,6,550135,1,prior,7,1,9,20.0,False,13032,...,Cinnamon Toast Crunch,121,14,4.0,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
38,7,3108588,1,prior,8,1,14,14.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
39,7,3108588,1,prior,8,1,14,14.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
40,7,3108588,1,prior,8,1,14,14.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
41,7,3108588,1,prior,8,1,14,14.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
42,7,3108588,1,prior,8,1,14,14.0,False,46149,...,Zero Calorie Cola,77,7,13.4,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
43,7,3108588,1,prior,8,1,14,14.0,False,49235,...,Organic Half & Half,53,16,1.8,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
44,8,2295261,1,prior,9,1,16,0.0,False,49235,...,Organic Half & Half,53,16,1.8,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
45,8,2295261,1,prior,9,1,16,0.0,False,46149,...,Zero Calorie Cola,77,7,13.4,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
46,8,2295261,1,prior,9,1,16,0.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
47,8,2295261,1,prior,9,1,16,0.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest Days,Most orders,10
48,8,2295261,1,prior,9,1,16,0.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
49,8,2295261,1,prior,9,1,16,0.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Busiest Days,Most orders,10
50,9,2550362,1,prior,10,4,8,30.0,False,196,...,Soda,77,7,9.0,both,Mid-range product,Least Day,Slowest Days,Average orders,10
51,9,2550362,1,prior,10,4,8,30.0,False,46149,...,Zero Calorie Cola,77,7,13.4,both,Mid-range product,Least Day,Slowest Days,Average orders,10
52,9,2550362,1,prior,10,4,8,30.0,False,39657,...,Milk Chocolate Almonds,45,19,6.8,both,Mid-range product,Least Day,Slowest Days,Average orders,10
53,9,2550362,1,prior,10,4,8,30.0,False,38928,...,0% Greek Strained Yogurt,120,16,12.6,both,Mid-range product,Least Day,Slowest Days,Average orders,10
54,9,2550362,1,prior,10,4,8,30.0,False,25133,...,Organic String Cheese,21,16,8.6,both,Mid-range product,Least Day,Slowest Days,Average orders,10
55,9,2550362,1,prior,10,4,8,30.0,False,10258,...,Pistachios,117,19,3.0,both,Low-range product,Least Day,Slowest Days,Average orders,10
56,9,2550362,1,prior,10,4,8,30.0,False,35951,...,Organic Unsweetened Almond Milk,91,16,1.3,both,Low-range product,Least Day,Slowest Days,Average orders,10
57,9,2550362,1,prior,10,4,8,30.0,False,13032,...,Cinnamon Toast Crunch,121,14,4.0,both,Low-range product,Least Day,Slowest Days,Average orders,10
58,9,2550362,1,prior,10,4,8,30.0,False,12427,...,Original Beef Jerky,23,19,4.4,both,Low-range product,Least Day,Slowest Days,Average orders,10
59,11,2168274,2,prior,1,2,11,NaN,True,32792,...,Chipotle Beef & Pork Realstick,23,19,5.2,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
60,11,2168274,2,prior,1,2,11,NaN,True,47766,...,Organic Avocado,24,4,6.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
61,11,2168274,2,prior,1,2,11,NaN,True,20574,...,Roasted Turkey,96,20,2.3,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
62,11,2168274,2,prior,1,2,11,NaN,True,12000,...,Baked Organic Sea Salt Crunchy Pea Snack,72,13,10.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
63,11,2168274,2,prior,1,2,11,NaN,True,48110,...,Thin Stackers Brown Rice Lightly Salted,78,19,2.7,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
64,11,2168274,2,prior,1,2,11,NaN,True,22474,...,Cheddar Bunnies Snack Crackers,78,19,4.1,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
65,11,2168274,2,prior,1,2,11,NaN,True,16589,...,Plantain Chips,107,19,5.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
66,11,2168274,2,prior,1,2,11,NaN,True,35917,...,Organic Just Concord Grape Juice,98,7,9.4,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
67,11,2168274,2,prior,1,2,11,NaN,True,27344,...,Uncured Genoa Salami,96,20,14.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
68,11,2168274,2,prior,1,2,11,NaN,True,30489,...,Original Hummus,67,20,7.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
69,11,2168274,2,prior,1,2,11,NaN,True,27966,...,Organic Raspberries,123,4,4.4,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
70,11,2168274,2,prior,1,2,11,NaN,True,13176,...,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
71,11,2168274,2,prior,1,2,11,NaN,True,45066,...,Honeycrisp Apple,24,4,2.5,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
72,12,1501582,2,prior,2,5,10,10.0,False,16797,...,Strawberries,24,4,1.3,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
73,12,1501582,2,prior,2,5,10,10.0,False,47526,...,Goat Cheese Log,21,16,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
74,12,1501582,2,prior,2,5,10,10.0,False,8479,...,Original Black Box Tablewater Cracker,78,19,3.5,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
75,12,1501582,2,prior,2,5,10,10.0,False,47766,...,Organic Avocado,24,4,6.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
76,12,1501582,2,prior,2,5,10,10.0,False,19051,...,"Pita Chips, Simply Naked, Party Size",107,19,3.9,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
77,12,1501582,2,prior,2,5,10,10.0,False,8138,...,Traditional Hummus,67,20,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
78,13,1901567,2,prior,3,1,10,3.0,False,47766,...,Organic Avocado,24,4,6.3,both,Mid-range product,Regularly busy,Busiest Days,Most orders,14
79,13,1901567,2,prior,3,1,10,3.0,False,32792,...,Chipotle Beef & Pork Realstick,23,19,5.2,both,Mid-range product,Regularly busy,Busiest Days,Most orders,14
80,13,1901567,2,prior,3,1,10,3.0,False,20574,...,Roasted Turkey,96,20,2.3,both,Low-range product,Regularly busy,Busiest Days,Most orders,14
81,13,1901567,2,prior,3,1,10,3.0,False,7781,...,Organic Sticks Low Moisture Part Skim Mozzarel...,21,16,6.6,both,Mid-range product,Regularly busy,Busiest Days,Most orders,14
82,13,1901567,2,prior,3,1,10,3.0,False,28874,...,Carrot Ginger Soup,1,20,6.2,both,Mid-range product,Regularly busy,Busiest Days,Most orders,14
83,14,738281,2,prior,4,2,10,8.0,False,49451,...,Artichoke Spinach Dip,67,20,7.1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
84,14,738281,2,prior,4,2,10,8.0,False,32792,...,Chipotle Beef & Pork Realstick,23,19,5.2,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
85,14,738281,2,prior,4,2,10,8.0,False,32139,...,Hommus Classic Original,67,20,7.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
86,14,738281,2,prior,4,2,10,8.0,False,34688,...,Good Belly Probiotics Juice Drink Blueberry Ac...,31,7,5.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
87,14,738281,2,prior,4,2,10,8.0,False,36735,...,Organic Roasted Sliced Chicken Breast,96,20,8.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
88,14,738281,2,prior,4,2,10,8.0,False,37646,...,Organic Gala Apples,24,4,9.1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
89,14,738281,2,prior,4,2,10,8.0,False,22829,...,Multigrain Flax Seeded Flatbread Crackers,78,19,5.5,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
90,14,738281,2,prior,4,2,10,8.0,False,24852,...,Banana,24,4,12.3,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
91,14,738281,2,prior,4,2,10,8.0,False,47209,...,Organic Hass Avocado,24,4,4.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
92,14,738281,2,prior,4,2,10,8.0,False,33276,...,Kalamata Olive Spread,67,20,10.8,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
93,14,738281,2,prior,4,2,10,8.0,False,45613,...,Pad Thai,38,1,12.6,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
94,14,738281,2,prior,4,2,10,8.0,False,9681,...,Chicken Tikka Masala with Cumin Infused Basmat...,38,1,2.0,both,Low-range product,Regularly busy,Regularly busy,Most orders,14
95,14,738281,2,prior,4,2,10,8.0,False,21150,...,Fire Grilled Steak Bowl,38,1,5.9,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
96,15,1673511,2,prior,5,3,11,8.0,False,47144,...,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,Mid-range product,Regularly busy,Slowest Days,Most orders,14
97,15,1673511,2,prior,5,3,11,8.0,False,5322,...,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,Low-range product,Regularly busy,Slowest Days,Most orders,14
98,15,1673511,2,prior,5,3,11,8.0,False,17224,...,Oats & Honey Gluten Free Granola,3,19,1.6,both,Low-range product,Regularly busy,Slowest Days,Most orders,14
99,15,1673511,2,prior,5,3,11,8.0,False,38656,...,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,Low-range product,Regularly busy,Slowest Days,Most orders,14

<H4>5. Deriving Columns with loc()</H4>

In [29]:
# New column is created,  flag customers who meet the criteria as 'loyal'
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [32]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] >10), 'loyalty_flag'] = 'Regular customer'

In [31]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [33]:
# Check value counts to check the frequency of the new loyalty flag
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [34]:
# Observation -Most customers fall into the 'Regular customer' category

In [35]:
# Check output 
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

In [36]:
# Export dataframe with newly derived columns
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merged_derived_new_variables.pkl'))

In [37]:
ords_prods_merge.shape

(32404859, 23)